// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh routes`.

import * as $0 from "./pages/[name].tsx";
import * as $1 from "./pages/api/joke.ts";
import * as $2 from "./pages/api/slowjoke.ts";
import * as $3 from "./pages/index.tsx";

const routes = {
  pages: {
    "./pages/[name].tsx": $0,
    "./pages/api/joke.ts": $1,
    "./pages/api/slowjoke.ts": $2,
    "./pages/index.tsx": $3,
  },
  baseUrl: import.meta.url,
};

export default routes;
